spring:
  application:
    name: SpringBootSample
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
    default: local
  messages:
    basename: messages,ValidationMessages

# log level
# logging:
  # file:
  #   path: ./
  #   name: sample.log
  # logback:
  #   rollingpolicy:
  #     max-file-size: 10KB
  #     max-history: 7
  #     file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz

# level:
#   '[com.example.demo]': debug
#   '[org.hibernate]': debug
#     SQL: debug
#     type:
#       '[descriptor.sql.BasicBinder]': trace
#       EnumType: trace

server:
  error:
    include-message: always
    include-stacktrace: always
    include-exception: true
    include-binding-errors: always